# Generated by Django 3.2.5 on 2021-11-08 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=250, verbose_name='theme_name')),
                ('map_img', models.ImageField(upload_to='images')),
                ('graph_img', models.ImageField(upload_to='images')),
                ('good', models.CharField(max_length=250, verbose_name='good_top3')),
                ('bad', models.CharField(max_length=250, verbose_name='bad_top3')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=250, verbose_name='place_name')),
                ('point', models.CharField(max_length=250, verbose_name='point')),
                ('graph_img', models.ImageField(upload_to='images')),
                ('wordcloud_img', models.ImageField(upload_to='images')),
                ('solutions', models.CharField(max_length=250, verbose_name='solutions')),
                ('map_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.theme')),
            ],
        ),
    ]
